---
name: codde_protocol
description: A starting point for Dart libraries or applications.
version: 0.1.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  flutter_rust_bridge: 2.0.0-dev.25
  uuid: ^4.2.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.8
  ffigen: ^9.0.1
  freezed: ^2.4.7
  lints: ^2.0.0
  mockito: ^5.4.2
  test: ^1.21.0
