[package]
name = "server_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codde_protocol = {path = "../.."}
pyo3 = {version ="0.20.2", features = ["anyhow", "serde"]}
