---
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/packages/codde_protocol"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/codde_protocol/example"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_codde_protocol"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_codde_protocol/example"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/codde_protocol/native"
    schedule:
      interval: weekly
