---
name: codde_protocol
description: Multi Communication protocol in heart of the C.O.D.D.E. Pi framework
version: 0.1.1+2
homepage: https://codde-pi.com

environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  build_runner: ^2.4.8
  ffigen: ^9.0.1
  freezed: ^2.4.7
  melos: ^4.1.0
  flutter_rust_bridge: 2.0.0-dev.24

flutter_rust_bridge:
  rust-input: packages/codde_protocol/native/src/api/**/*.rs
  dart-output: packages/codde_protocol/lib/src/rust
