---
name: codde_protocol_workspace
description: Multi Communication protocol in heart of the C.O.D.D.E. Pi framework
version: 0.1.3
homepage: https://codde-pi.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  melos: ^5.0.0
