[package]
name = "codde_protocol_derive"
version = "0.1.0"
edition = "2021"
authors = ["Mathis Lecomte <vm.lecomte@gmail.com>"]
homepage = "https://github.com/codde-pi/codde_protocol"
description = "Multi Communication protocol in heart of the C.O.D.D.E. Pi framework"
readme = "../../../../README.md"
license-file = "../../../../LICENSE"

[lib]
proc-macro = true

[dependencies]
syn = {version = "2.0", features = ["full"]}
quote = "1.0"


